#!/bin/bash
set -xv

# Check https://dnsviz.net/d/albandrieu.com/analyze/
# No DS records found for albandrieu.com in the com zone

# Remove
google._domainkey

"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsiiWZ64tWjV9X9xuamzYflMTkc5Tbp9IsMYGkJhTiXYVcH8lSeIQym/1OrHiuZZ4ZSHlHwhSsw6WPs6XjqjRlphp1CdzimzkTKb+HSOevA+OqTi28uaprtpd0DQD/VpLSH4vhhIKmDO" "T0/9hpkZ4qGdKkRzQbizHCWxG/VhkALkJqv6Zu1jb7TskgdEIJHL7nNUsy7d0fCABRhtUSpEHdkkdZiUZeXDOuf/HsGbEdAdGUSV58W4rDhzceknDqyj7Lk17GrgcBCilE75HqHqIi6UfJkbdUYqToM3hHFcpJrFJ7rZO9tSjFZvFmjejeptAp/Lqc3hiEAZ6mqtF/bvA" "DQIDAQAB"

google._domainkey

"v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsiiWZ64tWjV9X9xuamzYflMTkc5Tbp9IsMYGkJhTiXYVcH8lSeIQym/1OrHiuZZ4ZSHlHwhSsw6WPs6XjqjRlphp1CdzimzkTKb+HSOevA+OqTi28uaprtpd0DQD/VpLSH4vhhIKmDOT0/9hpkZ4qGdKkRzQbizHCWxG/VhkALkJqv6Zu1jb7TskgdEIJHL7n" "NUsy7d0fCABRhtUSpEHdkkdZiUZeXDOuf/HsGbEdAdGUSV58W4rDhzceknDqyj7Lk17GrgcBCilE75HqHqIi6UfJkbdUYqToM3hHFcpJrFJ7rZO9tSjFZvFmjejeptAp/Lqc3hiEAZ6mqtF/bvADQIDAQAB"

exit 0
